# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

targets = ['YFPopView_iOS','YFPopView_macOS']

targets.each do |t|
  target t do
    pod 'Masonry'
  end
end
